<a href="https://colab.research.google.com/github/shifasualeha/Data-Structures-and-Analytics/blob/main/lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#########################Task 1
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)
######################## Task 2
import numpy as np
X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]
print("Original Array:")
print(X)
print("\nArray with Odd Numbers:")
print(Y)









############################Task 3
import numpy as np

X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

######################### Task 4

from google.colab import drive
drive.mount('/NumPy.ipnyb')
import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)

# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array with Odd Numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
Drive already mounted at /NumPy.ipnyb; to attempt to forcibly remount, call drive.mount("/NumPy.ipnyb", force_remount=True).
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-1.3699412  -0.08934819  1.08869341 ...  1.57043768  0.12555198
  -1.48174449]
 [-0.78073946 -1.48689197  0.74212993 ...  0.08468112  1.50730239
  -0.50030862]
 [ 1.24873318  1.57601756 -0.06211959 ... -0.64033446  1.42133613
   0.5334338 ]
 ...
 [ 0.50959122  1.69149405 -0.32325761 ...  1.05487104  1.32907965
   1.19208326]
 [-1.76485419 -0.08586999 -1.62408607 ...  0.43633119  1.29972532
  -0.58358614]
 [ 1.35784461  1.32628226  0.5455819  ... -0.65364392 -1.73565254
  -0.46727291]]
Average 